### PR TITLE
New features added facebook login, user can share multiple secrets and see their secrets in their account.

### PR DESCRIPTION
**Pull request by gauravsingh1281**

### CODE REVIEW

**Review by Iamdivyak — APPROVED** [review]
image
  
can you please show me your change as this👆🏻

**Comment by gauravsingh1281** [comment]
Screenshot 2023-05-15 225938

Register Page ⬆️

**Comment by gauravsingh1281** [comment]
Screenshot 2023-05-15 230036

Login Page ⬆️

**Comment by gauravsingh1281** [comment]
Screenshot 2023-05-15 231236

Secret page with multiple user secrets ⬆️

**Comment by gauravsingh1281** [comment]
Screenshot 2023-05-15 231439

Now users can see their submitted secrets privately in their accounts.

**Comment by Iamdivyak** [comment]
thanks. Great job Gaurav🎉!

**Pull request merged**
